[package]
name = "horme"
version = "0.2.0"
authors = ["Marco Perin <marvin.themoodlifter@proton.me>"]
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.27.0"
ratatui = "0.27.0"
regex = "1.10.5"
strum = "0.26"
strum_macros = "0.26"
