[package]
name = "horme"
version = "0.1.0"
authors = ["Marco Perin <marvin.themoodlifter@proton.me>"]
edition = "2021"

[dependencies]
gtk = { version = "0.8", package = "gtk4", features = ["v4_14"] }
